---
- hosts: ws
  become: yes
  ignore_errors: yes
  vars_files: 
    - vars.yml
  tasks:
    - name: Download the ws package
      get_url:
        url: "{{ LINK_URL }}"
        dest: "{{ DESTINATION }}"
        
    - name: Delete file
      file:
        path: "{{ DESTINATION }}"
        state: absent